"""test ajout column location

Revision ID: 69cc915b61a8
Revises: 9468fe31fe04
Create Date: 2024-08-09 17:28:50.750944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '69cc915b61a8'
down_revision = '9468fe31fe04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'region')
    # ### end Alembic commands ###
