"""test migration 2

Revision ID: 9468fe31fe04
Revises: 70aa6f1bf45e
Create Date: 2024-08-09 17:26:48.038202

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9468fe31fe04'
down_revision = '70aa6f1bf45e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargepoint', sa.Column('ocpp_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chargepoint', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'chargepoint', 'location', ['location_id'], ['id'])
    op.add_column('paymentmethod', sa.Column('type_payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentmethod', 'type_payment_method')
    op.drop_constraint(None, 'chargepoint', type_='foreignkey')
    op.drop_column('chargepoint', 'name')
    op.drop_column('chargepoint', 'ocpp_version')
    # ### end Alembic commands ###
