""" correction migration

Revision ID: 3ea3b7bc32ad
Revises: None
Create Date: 2024-08-12 10:14:26.125962

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3ea3b7bc32ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargepoint', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chargepoint', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_chargepoint_id', 'chargepoint', ['id'], unique=False)
    op.create_foreign_key(None, 'chargepoint', 'location', ['location_id'], ['id'])
    op.add_column('connector', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('connector', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_connector_id', 'connector', ['id'], unique=False)
    op.add_column('contract', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contract', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_contract_id', 'contract', ['id'], unique=False)
    op.add_column('location', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('location', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_location_id', 'location', ['id'], unique=False)
    op.add_column('partner', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('partner', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_partner_id', 'partner', ['id'], unique=False)
    op.add_column('paymentmethod', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('paymentmethod', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_paymentmethod_id', 'paymentmethod', ['id'], unique=False)
    op.add_column('paymentmethoduser', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('paymentmethoduser', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_paymentmethoduser_id', 'paymentmethoduser', ['id'], unique=False)
    op.add_column('session', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_session_id', 'session', ['id'], unique=False)
    op.add_column('subscription', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subscription', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_subscription_id', 'subscription', ['id'], unique=False)
    op.add_column('tag', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_tag_id', 'tag', ['id'], unique=False)
    op.add_column('tariff', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tariff', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_tariff_id', 'tariff', ['id'], unique=False)
    op.add_column('tariffgroup', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tariffgroup', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_tariffgroup_id', 'tariffgroup', ['id'], unique=False)
    op.add_column('tariffsnapshot', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tariffsnapshot', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_tariffsnapshot_id', 'tariffsnapshot', ['id'], unique=False)
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('transaction', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_transaction_id', 'transaction', ['id'], unique=False)
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.add_column('usergroup', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('usergroup', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_usergroup_id', 'usergroup', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usergroup_id', table_name='usergroup')
    op.drop_column('usergroup', 'updated_at')
    op.drop_column('usergroup', 'created_at')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_index('ix_transaction_id', table_name='transaction')
    op.drop_column('transaction', 'updated_at')
    op.drop_column('transaction', 'created_at')
    op.drop_index('ix_tariffsnapshot_id', table_name='tariffsnapshot')
    op.drop_column('tariffsnapshot', 'updated_at')
    op.drop_column('tariffsnapshot', 'created_at')
    op.drop_index('ix_tariffgroup_id', table_name='tariffgroup')
    op.drop_column('tariffgroup', 'updated_at')
    op.drop_column('tariffgroup', 'created_at')
    op.drop_index('ix_tariff_id', table_name='tariff')
    op.drop_column('tariff', 'updated_at')
    op.drop_column('tariff', 'created_at')
    op.drop_index('ix_tag_id', table_name='tag')
    op.drop_column('tag', 'updated_at')
    op.drop_column('tag', 'created_at')
    op.drop_index('ix_subscription_id', table_name='subscription')
    op.drop_column('subscription', 'updated_at')
    op.drop_column('subscription', 'created_at')
    op.drop_index('ix_session_id', table_name='session')
    op.drop_column('session', 'updated_at')
    op.drop_column('session', 'created_at')
    op.drop_index('ix_paymentmethoduser_id', table_name='paymentmethoduser')
    op.drop_column('paymentmethoduser', 'updated_at')
    op.drop_column('paymentmethoduser', 'created_at')
    op.drop_index('ix_paymentmethod_id', table_name='paymentmethod')
    op.drop_column('paymentmethod', 'updated_at')
    op.drop_column('paymentmethod', 'created_at')
    op.drop_index('ix_partner_id', table_name='partner')
    op.drop_column('partner', 'updated_at')
    op.drop_column('partner', 'created_at')
    op.drop_index('ix_location_id', table_name='location')
    op.drop_column('location', 'updated_at')
    op.drop_column('location', 'created_at')
    op.drop_index('ix_contract_id', table_name='contract')
    op.drop_column('contract', 'updated_at')
    op.drop_column('contract', 'created_at')
    op.drop_index('ix_connector_id', table_name='connector')
    op.drop_column('connector', 'updated_at')
    op.drop_column('connector', 'created_at')
    op.drop_constraint(None, 'chargepoint', type_='foreignkey')
    op.drop_index('ix_chargepoint_id', table_name='chargepoint')
    op.drop_column('chargepoint', 'updated_at')
    op.drop_column('chargepoint', 'created_at')
    # ### end Alembic commands ###
